# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GOJswIzj-wjmbKVWycNoOBZFKv6ux3wW
"""

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
import os

# Create flask app
flask_app = Flask(__name__)
model = pickle.load(open("C:\\Users\\Viswambharan\\OneDrive\\Desktop\\Model Deployment\\model.pkl", "rb"))

@flask_app.route("/")
def Home():
    return render_template("index1.html")

@flask_app.route("/predict", methods = ["POST"])
def predict():
    float_features = [float(x) for x in request.form.values()]
    features = [np.array(float_features)]
    prediction = model.predict(features)
    return render_template("index1.html", prediction_text = "Personal Loan prediction is {}".format(prediction))

if __name__ == "__main__":
  flask_app.run(debug=True)

#if __name__ == "__main__":
  #flask_app.run(host='localhost', port=5000, debug=True,use_reloader = False)

#if __name__ == "__main__":
  #port = int(os.environ.get('PORT', 5000))
  #flask_app.run(host='0.0.0.0', port=port)

